---
abstract: 'List prereqs conditional on operating system'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Dist::Zilla::Tester: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  JSON: '2'
  List::Util: '0'
  Params::Util: '0'
  Path::Class: '0'
  Sub::Exporter: '0'
  Test::Deep: '0'
  Test::More: '0.88'
  YAML::Tiny: '0'
  lib: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-OSPrereqs-Prefix
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::OSPrereqs::Prefix:
    file: lib/Dist/Zilla/Plugin/OSPrereqs/Prefix.pm
    version: '0.004'
requires:
  Dist::Zilla::Role::InstallTool: '0'
  Dist::Zilla::Role::MetaProvider: '0'
  List::AllUtils: '0'
  Moose: '0'
  namespace::autoclean: '0'
  perl: '5.008001'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/sharyanto/operl-Dist-Zilla-Plugin-OSPrereqs/issues
  homepage: https://github.com/sharyanto/operl-Dist-Zilla-Plugin-OSPrereqs
  repository: https://github.com/sharyanto/operl-Dist-Zilla-Plugin-OSPrereqs.git
version: '0.004'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Dave Rolsky <autarch@urth.org>'
  - 'David Golden <dagolden@cpan.org>'
  - 'Ioan Rogers <ioanr@cpan.org>'
  - 'Steven Haryanto (on Asus Zenbook) <stevenharyanto@gmail.com>'
  - 'Steven Haryanto (on PC, Bandung) <stevenharyanto@gmail.com>'
